name=MidiController
version=0.1.0
author=kenz67
maintainer=kenz67
sentence=Arduino MIDI controller library for buttons and potentiometers.
paragraph=A library for creating MIDI controllers on Arduino. Supports various button types (Note, Control, Latch, SimLatch) and potentiometers to send MIDI messages over USB. Developed for Arduino Leonardo with potential compatibility for other boards.
category=Communication
url=https://github.com/kenz67/MidiController
architectures=leonardo,avr
depends=MIDIUSB
